name: wildfire
description: An Conduit application with a database connection and data model.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  conduit: ^2.0.0-b1

dev_dependencies:
  test: ^1.0.0
  conduit_test: ^2.0.0-b1

dependency_overrides:
  conduit_test: 
    path: ../../../conduit_test

  conduit: 
    path: ../../../conduit



